[plugin]
repository = "https://github.com/SalvatoreDevelopment/AetherFM.git"
commit = "163ace4a7d5792b76c91cfad682917037e6e6428"
owners = ["SalvatoreDevelopment"]
project_path = "."
changelog = "Initial release with Radio Browser API integration. Modern UI with search, filters, and volume controls. Automatic station loading and duplicate filtering. Comprehensive error handling and user feedback. Developer workflow automation with build scripts. Support for English and Italian languages." 